const ALPHABET = {
    A: {LETTER: 'A'},
    B: {LETTER: 'B'},
    C: {LETTER: 'C'},
    D: {LETTER: 'D'},
    E: {LETTER: 'E'},
    F: {LETTER: 'F'},
    G: {LETTER: 'G'},
    H: {LETTER: 'H'},
    I: {LETTER: 'I'},
    J: {LETTER: 'J'},
    K: {LETTER: 'K'},
    L: {LETTER: 'L'},
    M: {LETTER: 'M'},
    N: {LETTER: 'N'},
    O: {LETTER: 'O'},
    P: {LETTER: 'P'},
    Q: {LETTER: 'Q'},
    R: {LETTER: 'R'},
    S: {LETTER: 'S'},
    T: {LETTER: 'T'},
    U: {LETTER: 'U'},
    V: {LETTER: 'V'},
    W: {LETTER: 'W'},
    X: {LETTER: 'X'},
    Y: {LETTER: 'Y'},
    Z: {LETTER: 'Z'},
};

const ARRAY_ALPHABET = [
    {LETTER: 'A'},
    {LETTER: 'B'},
    {LETTER: 'C'},
    {LETTER: 'D'},
    {LETTER: 'E'},
    {LETTER: 'F'},
    {LETTER: 'G'},
    {LETTER: 'H'},
    {LETTER: 'I'},
    {LETTER: 'J'},
    {LETTER: 'K'},
    {LETTER: 'L'},
    {LETTER: 'M'},
    {LETTER: 'N'},
    {LETTER: 'O'},
    {LETTER: 'P'},
    {LETTER: 'Q'},
    {LETTER: 'R'},
    {LETTER: 'S'},
    {LETTER: 'T'},
    {LETTER: 'U'},
    {LETTER: 'V'},
    {LETTER: 'W'},
    {LETTER: 'X'},
    {LETTER: 'Y'},
    {LETTER: 'Z'},
];

export { ARRAY_ALPHABET, ALPHABET};